### ISSUE TITLE
request for a line change to work with stand alone xrootd server in addition to EOS server

### ISSUE THREAD

**Issue by dougbenjamin** [ivmfnal/ftslight#1]
https://github.com/ivmfnal/ftslight/blob/10a24546660786d52fdf2ea7616cf628e7e9d4fc/FTSLight3/Scanner.py#L169

change line to be: 

if t in "f-" or t == "-":

**Comment by ivmfnal** [comment]
`t in "f-"` is equivalent to `t == 'f' or t == '-'`:
```
>>> t = '-'
>>> t in "f-"
True
```

**Comment by dougbenjamin** [comment]
OK
